openapi: 3.0.1
info:
  title: TextAPI
  description: API Definition of TextAPI
  version: 1.0.0
servers:
  - url: http://localhost:8290/textapi
  - url: https://localhost:8253/textapi
paths:
  /hello:
    get:
      responses:
        default:
          description: Default response
